import { Box, Flex, Text } from '@chakra-ui/react';
import Head from 'next/head';

import Footer from '../components/Footer';

const Booking = () => {
  return (
    <Box bg="primary.codgray">
      <Head>
        <title>Dine - Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex role="main" direction="column" align="center" bg="white" p="16">
        <Text color="primary.codgray">Hello</Text>
      </Flex>

      <Footer />
    </Box>
  );
};

export default Booking;
