import { Box, Flex, Heading, Text } from '@chakra-ui/react';
import Head from 'next/head';

import CustomLink from '../components/CustomLink';
import Footer from '../components/Footer';
import Logo from '../components/Logo';
import ReservationForm from '../components/ReservationForm';

const Booking = () => {
  return (
    <Box bg="primary.codgray">
      <Head>
        <title>Dine - Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        role="main"
        direction="column"
        align="center"
        bg="white"
        bgImage={{
          base: '/images/hero-bg-mobile@2x.jpg',
          md: '/images/hero-bg-tablet@2x.jpg',
          xl: '/images/hero-bg-desktop@2x.jpg',
        }}
        bgRepeat="no-repeat"
        bgPos="center"
        bgSize="cover"
        pt="12"
      >
        <Logo />
        <Heading as="h1" variant="h1" color="white" mb="6">
          Reservations
        </Heading>
        <Text textStyle="body2" color="white" textAlign="center" mb="6">
          We can’t wait to host you. If you have any special requirements please
          feel free to call on the phone number below. We’ll be happy to
          accommodate you.
        </Text>
        <CustomLink href="/" variant="dark" mb="220px">
          Reserve place
        </CustomLink>
        <Box w="full" bg="white" px="6">
          <ReservationForm />
        </Box>
      </Flex>

      <Footer />
    </Box>
  );
};

export default Booking;
