import { Box, Flex, Heading, Text } from '@chakra-ui/react';
import Head from 'next/head';
import PatternDivider from '../components/patterns/PatternDivider';

import Hero from '../components/Hero';
import Main from '../components/Main';
import MainAlt from '../components/MainAlt';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Dine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex role="main" direction="column" align="center">
        <Hero />
        <MainAlt />
        {/* <Main /> */}
      </Flex>
    </Box>
  );
}
