import { Box, Flex } from '@chakra-ui/react';
import Head from 'next/head';

import Hero from '../components/Hero';
import Main from '../components/Main';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Dine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex role="main" bg="red.200" direction="column">
        <Hero />
        <Main />
      </Flex>
    </Box>
  );
}
